### ISSUE TITLE
Bintray binaries ought to be statically linked

### ISSUE THREAD

**Issue by relistan** [jfrog/goc#7]
These would be great to use when building in Docker containers, but if you try to run them on Alpine Linux (one of the most common container platform), they don't work because they're linked against glibc and libpthread.

```
/go # ldd goc
/lib64/ld-linux-x86-64.so.2 (0x7f7ba3e10000)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7ba3e10000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7ba3e10000)
```

Ideally these would be built with: `go build -ldflags '-w -extldflags "-static"'` which would allow them to run on any Linux platform with the specified CPU architecture.

The Go project supports two build container image streams and one of them is based on Alpine. If you want to try it out yourself, here's the image `golang:1.11-alpine3.8`

**Comment by eyalbe4** [comment]
@relistan,
Thank you for sharing this and getting involved! 
I think that JFrog CLI's official docker image resolves this issue, by using [this](https://github.com/jfrog/jfrog-cli-go/blob/master/Dockerfile) Dockerfile.
Would you like to try out that approach? I believe that you'll need to replace in that Dockerfile *jfrog-cli-go* with *goc*.
If indeed that works (I believe it should, but let me know what you think), feel free to create a pull request with the Dockerfile for goc and we'll be able to add the image creating to goc's release process.
Let me know what you think.

**Comment by relistan** [comment]
Finally got back to this @eyalbe4 and I don't think that file is going to help. You need to build the utils themselves with the correct flags to be static binaries. `CGO_ENABLED=0` can help make that happen but isn't sufficient on its own.

**Comment by eyalbe4** [comment]
@relistan - thanks for sharing this info.
We've just implemented this for JFrog CLI - see https://github.com/jfrog/jfrog-cli-go/issues/328
We plan to implement the same solution (see the *build.sh* file referenced from the above issue) for **goc**.

**Comment by rimusz** [comment]
@eyalbe4 any updates on statically linked goc binary release?
