### ISSUE TITLE
goc appears to munge ldflags when passed through it

### ISSUE THREAD

**Issue by relistan** [jfrog/goc#8]
When attempting to build static binaries using `goc` to build, I see the following:

```
$ ./goc build -ldflags '-w -extldflags "-static"'
flag provided but not defined: -extldflags
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```

It appears to me that the quoting around `'-w -extldflags "-static"'` may somehow be getting munged when passed through `goc`.

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @relistan!
We're currently working on a fix.
We'll let you know when it is ready.

**Comment by relistan** [comment]
Awesome, thanks!

**Comment by eyalbe4** [comment]
@relistan,
@AlexeiVainshtein fixed the issue and released *goc 1.0.3*.
Thanks @AlexeiVainshtein!

**Comment by relistan** [comment]
Excellent, will try it out. Thanks!

**Comment by relistan** [comment]
Confirmed working. Thanks!
